"""Generate the curated-image pool plan from the spec.

Outputs two files, both under var/:
  - curated_pool_plan.json   — structured input consumed by the batch-submit
                                and upload scripts downstream.
  - curated_pool_taxonomy.md — human-readable table for review before any
                                money is spent on generation.

This is a pure builder — no API calls, no cost. Safe to re-run.

Usage:
    ./venv/bin/python scripts/build_curated_pool_plan.py
"""

from __future__ import annotations

import json
from pathlib import Path

from app.writer.curated_pool_spec import build_pool_items, pool_size

VAR_DIR = Path(__file__).resolve().parent.parent / "var"
PLAN_JSON = VAR_DIR / "curated_pool_plan.json"
TAXONOMY_MD = VAR_DIR / "curated_pool_taxonomy.md"


def main() -> None:
    VAR_DIR.mkdir(parents=True, exist_ok=True)
    items = build_pool_items()
    assert len(items) == pool_size(), "spec mismatch"

    plan_rows = [
        {
            "slug": item.slug,
            "team_code": item.team_code,
            "scene": item.scene,
            "description": item.description,
            "prompt": item.prompt,
            "output_filename": f"{item.slug}.png",
        }
        for item in items
    ]
    PLAN_JSON.write_text(json.dumps(plan_rows, indent=2, ensure_ascii=False))

    # Markdown taxonomy — one section per team + one generic section
    lines: list[str] = []
    lines.append(f"# Curated Image Pool Plan ({len(items)} images)\n")
    lines.append(
        "This document is the human-readable view of `curated_pool_plan.json`.\n"
        "Generated by `scripts/build_curated_pool_plan.py` — do not edit by "
        "hand. Edit `app/writer/curated_pool_spec.py` instead and re-run.\n"
    )

    team_items = [i for i in items if i.team_code is not None]
    generic_items = [i for i in items if i.team_code is None]

    lines.append(f"## Team-specific ({len(team_items)} images)\n")
    lines.append("7 scenes per team × 32 teams.\n")
    lines.append("| Slug | Team | Scene | Description |")
    lines.append("|---|---|---|---|")
    for item in team_items:
        lines.append(
            f"| `{item.slug}` | {item.team_code} | {item.scene} | "
            f"{item.description} |"
        )

    lines.append(f"\n## Generic ({len(generic_items)} images)\n")
    lines.append("Hand-picked scenes for league-wide / fallback stories.\n")
    lines.append("| Slug | Scene | Description |")
    lines.append("|---|---|---|")
    for item in generic_items:
        lines.append(f"| `{item.slug}` | {item.scene} | {item.description} |")

    lines.append("\n## Sample prompts (one per scene)\n")
    seen_scenes: set[str] = set()
    for item in items:
        if item.scene in seen_scenes:
            continue
        seen_scenes.add(item.scene)
        lines.append(f"### `{item.scene}` — {item.description}")
        lines.append("```")
        lines.append(item.prompt)
        lines.append("```\n")

    TAXONOMY_MD.write_text("\n".join(lines))

    print(f"Wrote {PLAN_JSON}  ({len(items)} rows)")
    print(f"Wrote {TAXONOMY_MD}")


if __name__ == "__main__":
    main()
