"""End-to-end deliver: read row → upload → patch row → cleanup audio.

The boundary between produce and deliver: produce leaves a `rendered`
row with a local audio path; deliver picks it up, ships to Spotify,
marks the row `delivered`, and deletes the audio file.

Failure mode: if the upload fails, the row is marked `failed` with
the error message; the audio file is intentionally NOT deleted so a
manual re-deliver via the CLI can retry without re-rendering.
"""

from __future__ import annotations

import logging
from pathlib import Path

from app.adapters import PodcastEpisodeWriter
from app.config import Settings
from app.delivery.schemas import DeliveryResult
from app.delivery.spotify import SaveToSpotifyDelivery

logger = logging.getLogger(__name__)


def _fallback_title(run_date: str, language: str) -> str:
    return f"T4L Daily — {run_date} ({language})"


def _fallback_summary(
    run_date: str, story_count: int, duration_seconds: int | None
) -> str:
    duration_str = (
        f"{duration_seconds // 60} min" if duration_seconds else "varies"
    )
    return (
        f"Personal NFL daily briefing for {run_date}. "
        f"{story_count} stories · {duration_str} · "
        f"two-host morning format (Marcus + Robin). "
        f"Generated by the T4L editorial cycle."
    )


async def dispatch_episode(
    episode_id: int,
    *,
    settings: Settings,
    dry_run: bool = False,
) -> DeliveryResult:
    """Read an episode row, upload to Spotify, patch state, cleanup audio."""
    base_url = str(settings.supabase_url).rstrip("/")
    service_role_key = settings.supabase_service_role_key.get_secret_value()
    writer = PodcastEpisodeWriter(
        base_url=base_url, service_role_key=service_role_key
    )

    try:
        record = await writer.get(episode_id)
        if record.status != "rendered":
            return DeliveryResult(
                success=False,
                error_message=(
                    f"episode #{episode_id} status is {record.status!r}, "
                    "expected 'rendered'"
                ),
            )
        if not record.audio_local_path:
            return DeliveryResult(
                success=False,
                error_message=(
                    f"episode #{episode_id} has no audio_local_path "
                    "(was it produced with --dry-run?)"
                ),
            )

        # Prefer per-episode LLM-generated metadata from the row.
        # Fall back to a deterministic template when those columns
        # are NULL (e.g. older rows produced before the metadata
        # agent was wired in).
        title = record.episode_title or _fallback_title(
            record.run_date.isoformat(), record.language
        )
        summary = record.episode_summary or _fallback_summary(
            record.run_date.isoformat(),
            record.story_count,
            record.duration_seconds,
        )

        delivery = SaveToSpotifyDelivery(settings)
        result = await delivery.dispatch(
            audio_path=record.audio_local_path,
            title=title,
            summary=summary,
            language=record.language,
            dry_run=dry_run,
        )

        if dry_run:
            return result

        if result.success:
            await writer.mark_delivered(
                episode_id, spotify_episode_id=result.spotify_episode_id
            )
            # Cleanup: delete the local audio file. Keep the row id +
            # spotify_episode_id as the audit trail.
            try:
                Path(record.audio_local_path).unlink(missing_ok=True)
                logger.info("Removed local audio %s", record.audio_local_path)
            except OSError as exc:
                logger.warning(
                    "Failed to remove local audio %s: %s",
                    record.audio_local_path, exc,
                )
        else:
            await writer.mark_failed(
                episode_id, error_message=result.error_message or "unknown delivery error"
            )

        return result
    finally:
        await writer.close()
